
CREATE TABLE CAR_BRAND
(
  BRAND_NAME VARCHAR(50) NOT NULL,
  BRAND_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (BRAND_CODE)
);

CREATE TABLE CAR_COMPANY
(
  COMPANY_NAME VARCHAR(50) NOT NULL,
  COMPANY_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (COMPANY_CODE)
);

CREATE TABLE CAR_OPTION
(
  OPTION_TYPE VARCHAR(50) NOT NULL,
  OPTION_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (OPTION_CODE)
);

CREATE TABLE CARS
(
  CAR_ID       VARCHAR(50) NOT NULL,
  COMPANY_CODE VARCHAR(50) NOT NULL,
  BRAND_CODE   VARCHAR(50) NOT NULL,
  RELEASE_YEAR INTEGER     NOT NULL,
  PRIMARY KEY (CAR_ID)
);

CREATE TABLE SELECTED_OPTIONS
(
  CAR_ID      VARCHAR(50) NOT NULL,
  OPTION_CODE VARCHAR(50) NOT NULL
);

ALTER TABLE CARS
  ADD CONSTRAINT FK_CAR_COMPANY_TO_CARS
    FOREIGN KEY (COMPANY_CODE)
    REFERENCES CAR_COMPANY (COMPANY_CODE);

ALTER TABLE CARS
  ADD CONSTRAINT FK_CAR_BRAND_TO_CARS
    FOREIGN KEY (BRAND_CODE)
    REFERENCES CAR_BRAND (BRAND_CODE);

ALTER TABLE SELECTED_OPTIONS
  ADD CONSTRAINT FK_CARS_TO_SELECTED_OPTIONS
    FOREIGN KEY (CAR_ID)
    REFERENCES CARS (CAR_ID);

ALTER TABLE SELECTED_OPTIONS
  ADD CONSTRAINT FK_CAR_OPTION_TO_SELECTED_OPTIONS
    FOREIGN KEY (OPTION_CODE)
    REFERENCES CAR_OPTION (OPTION_CODE);
