
CREATE TABLE CHECKUP_RESULT
(
  ABNORMALITY VARCHAR(50) NOT NULL,
  RESULT_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (RESULT_CODE)
) COMMENT '검진결과';

CREATE TABLE GENDER_CODE
(
  GENDER_TITLE VARCHAR(50) NOT NULL,
  GENDER_CODE  VARCHAR(50) NOT NULL,
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별';

CREATE TABLE PATIENT
(
  NAME              VARCHAR(50) NOT NULL,
  AGE               INTEGER     NOT NULL,
  HEIGHT            INTEGER     NOT NULL,
  WEIGHT            INTEGER     NOT NULL,
  BLOOD_PRESSURE    INTEGER     NOT NULL,
  BLOOD_SUGAR_LEVEL INTEGER     NOT NULL,
  PATIENT_CODE      VARCHAR(50) NOT NULL,
  GENDER_CODE       VARCHAR(50) NOT NULL,
  RESULT_CODE       VARCHAR(50) NOT NULL,
  PRIMARY KEY (PATIENT_CODE)
) COMMENT '환자 리스트';

CREATE TABLE POSSIBLE_DISEASE
(
  ILLNESS_NAME          VARCHAR(50) NOT NULL,
  POSSIBLE_DISEASE_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (POSSIBLE_DISEASE_CODE)
) COMMENT '재검진 항목';

CREATE TABLE POSSIBLE_IMPROVEMENT
(
  IMPROVEMENT_CONTENT VARCHAR(50) NOT NULL,
  IMPROVEMENT_CODE    VARCHAR(50) NOT NULL,
  PRIMARY KEY (IMPROVEMENT_CODE)
) COMMENT '유지방안';

CREATE TABLE RE_CHECKUP
(
  PATIENT_CODE          VARCHAR(50) NOT NULL,
  POSSIBLE_DISEASE_CODE VARCHAR(50) NOT NULL
) COMMENT '재검진';

CREATE TABLE SUGGESTION
(
  IMPROVEMENT_CODE VARCHAR(50) NOT NULL,
  PATIENT_CODE     VARCHAR(50) NOT NULL
) COMMENT '유지';

ALTER TABLE PATIENT
  ADD CONSTRAINT FK_GENDER_CODE_TO_PATIENT
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE RE_CHECKUP
  ADD CONSTRAINT FK_POSSIBLE_DISEASE_TO_RE_CHECKUP
    FOREIGN KEY (POSSIBLE_DISEASE_CODE)
    REFERENCES POSSIBLE_DISEASE (POSSIBLE_DISEASE_CODE);

ALTER TABLE RE_CHECKUP
  ADD CONSTRAINT FK_PATIENT_TO_RE_CHECKUP
    FOREIGN KEY (PATIENT_CODE)
    REFERENCES PATIENT (PATIENT_CODE);

ALTER TABLE PATIENT
  ADD CONSTRAINT FK_CHECKUP_RESULT_TO_PATIENT
    FOREIGN KEY (RESULT_CODE)
    REFERENCES CHECKUP_RESULT (RESULT_CODE);

ALTER TABLE SUGGESTION
  ADD CONSTRAINT FK_POSSIBLE_IMPROVEMENT_TO_SUGGESTION
    FOREIGN KEY (IMPROVEMENT_CODE)
    REFERENCES POSSIBLE_IMPROVEMENT (IMPROVEMENT_CODE);

ALTER TABLE SUGGESTION
  ADD CONSTRAINT FK_PATIENT_TO_SUGGESTION
    FOREIGN KEY (PATIENT_CODE)
    REFERENCES PATIENT (PATIENT_CODE);
