
CREATE TABLE ADDRESS
(
  MUNICIPALITY_NAME VARCHAR(50) NOT NULL,
  ADDRESS_CODE_ID   VARCHAR(50) NOT NULL,
  PRIMARY KEY (ADDRESS_CODE_ID)
);

CREATE TABLE GENDER
(
  GENDER_TITLE   VARCHAR(50) NOT NULL,
  GENDER_CODE_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (GENDER_CODE_ID)
);

CREATE TABLE HOBBY_CODE
(
  HOBBY_NAME    VARCHAR(500) NULL     COMMENT '취미명칭',
  HOBBY_CODE_ID VARCHAR(50)  NOT NULL,
  PRIMARY KEY (HOBBY_CODE_ID)
);

CREATE TABLE MEMBER_EMAIL
(
  EMAIL_ADDRESS   VARCHAR(50) NOT NULL COMMENT '이메일 주소',
  MEMBER_EMAIL_ID VARCHAR(50) NOT NULL,
  MEMBER_ID       VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (MEMBER_EMAIL_ID)
) COMMENT '이메일';

CREATE TABLE MEMBER_HOBBY
(
  MEMBER_ID     VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  HOBBY_CODE_ID VARCHAR(50) NOT NULL
) COMMENT '취미';

CREATE TABLE MEMBER_INFO
(
  NAME            VARCHAR(50) NOT NULL COMMENT '이름',
  AGE             INTEGER     NOT NULL COMMENT '나이',
  MOBILE_NUMBER   VARCHAR(50) NOT NULL COMMENT '전화번호',
  MEMBER_ID       VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  GENDER_CODE_ID  VARCHAR(50) NOT NULL,
  ADDRESS_CODE_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (MEMBER_ID)
) COMMENT '회원정보';

ALTER TABLE MEMBER_HOBBY
  ADD CONSTRAINT FK_MEMBER_INFO_TO_MEMBER_HOBBY
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER_INFO (MEMBER_ID);

ALTER TABLE MEMBER_EMAIL
  ADD CONSTRAINT FK_MEMBER_INFO_TO_MEMBER_EMAIL
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER_INFO (MEMBER_ID);

ALTER TABLE MEMBER_HOBBY
  ADD CONSTRAINT FK_HOBBY_CODE_TO_MEMBER_HOBBY
    FOREIGN KEY (HOBBY_CODE_ID)
    REFERENCES HOBBY_CODE (HOBBY_CODE_ID);

ALTER TABLE MEMBER_INFO
  ADD CONSTRAINT FK_GENDER_TO_MEMBER_INFO
    FOREIGN KEY (GENDER_CODE_ID)
    REFERENCES GENDER (GENDER_CODE_ID);

ALTER TABLE MEMBER_INFO
  ADD CONSTRAINT FK_ADDRESS_TO_MEMBER_INFO
    FOREIGN KEY (ADDRESS_CODE_ID)
    REFERENCES ADDRESS (ADDRESS_CODE_ID);
