SELECT T_MEMS.*, T_MEMS_LOGIN.EMAIL, T_GENDERS.GENDER
FROM (members AS T_MEMS
INNER JOIN members_login AS T_MEMS_LOGIN
ON T_MEMS.MEMBERS_ID = T_MEMS_LOGIN.MEMBERS_ID)
INNER JOIN gender_code AS T_GENDERS
ON T_MEMS.GENDER_CODE_ID = T_GENDERS.GENDER_CODE_ID
WHERE T_MEMS.MEMBERS_ID = 'M-02';

SELECT T_MEMS.*, T_MEMS_LOGIN.EMAIL, T_GENDERS.GENDER
FROM (members AS T_MEMS
INNER JOIN members_login AS T_MEMS_LOGIN
ON T_MEMS.MEMBERS_ID = T_MEMS_LOGIN.MEMBERS_ID
AND T_MEMS.MEMBERS_ID = 'M-02')
INNER JOIN gender_code AS T_GENDERS
ON T_MEMS.GENDER_CODE_ID = T_GENDERS.GENDER_CODE_ID