SELECT T_SELLERS.FIRST, T_SELLERS.SECOND, T_BUYERS.TOTAL_ORDER, T_BUYERS.LAST
FROM
(SELECT T_CUS.CustomerID, T_ORD.OrderID, T_CUS.CustomerName AS LAST, count(*) AS TOTAL_ORDER
FROM Customers AS T_CUS
	INNER JOIN Orders AS T_ORD
    ON T_CUS.CustomerID = T_ORD.CustomerID
    GROUP BY T_CUS.CustomerID) AS T_BUYERS
	INNER JOIN
(SELECT T_PRO.ProductID , T_DET.Quantity, T_DET.OrderID, T_PRO.ProductName AS FIRST, T_PRO.Price AS SECOND
FROM Products AS T_PRO   
    INNER JOIN OrderDetails AS T_DET
	ON T_PRO.ProductID = T_DET.ProductID) AS T_SELLERS
    ON T_BUYERS.OrderID = T_SELLERS.OrderID
    ;